
package group1j.ReviewTool.UserInterface.screens;

/**
 * @author anilt
 * This is the LoginScreen class
 * which holds UI code generated by the
 * NetBeans UI Builder and event handling
 * code for the UI.
 */

import group1j.ReviewTool.UserInterface.UIController;
import javax.swing.*;
public class LoginScreen extends JFrame implements ScreenInterface{

    /**
     * Creates new form LoginScreen
     */
    
    public void refreshUI(){
        this.revalidate();
    }
    
    public LoginScreen() {
        
        initComponents();
        whiteBgLabel.setIcon(new javax.swing.ImageIcon("src\\main\\java\\group1j\\ReviewTool\\UserInterface\\img\\whiteBackground.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        blueBgPanel = new javax.swing.JPanel();
        whiteBgPanel = new javax.swing.JPanel();
        mailField = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        signupButton.setFocusPainted(false);
        loginButton = new javax.swing.JButton();
        loginButton.setFocusPainted(false);
        titleLabel = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();
        errorLabel.setVisible(false);
        mailLabel = new javax.swing.JLabel();
        pwLabel = new javax.swing.JLabel();
        whiteBgLabel = new javax.swing.JLabel();
        blueBg = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ReviewTool");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blueBgPanel.setBackground(new java.awt.Color(71, 120, 197));
        blueBgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whiteBgPanel.setPreferredSize(new java.awt.Dimension(200, 100));
        whiteBgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mailField.setActionCommand("<Not Set>");
        mailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        whiteBgPanel.add(mailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, -1));

        signupButton.setText("Signup");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        whiteBgPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        whiteBgPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("     ReviewTool");
        whiteBgPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 201, 59));

        pwField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        whiteBgPanel.add(pwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 20));

        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setText("Invalid E-Mail or Password");
        whiteBgPanel.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 230, 40));

        mailLabel.setText("    Mail Address:");
        whiteBgPanel.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 40));

        pwLabel.setText("Password:");
        whiteBgPanel.add(pwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 33));
        whiteBgPanel.add(whiteBgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        blueBgPanel.add(whiteBgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 310, 490));
        blueBgPanel.add(blueBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 640));

        getContentPane().add(blueBgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        UIController.changeScreen("signup");
        this.setVisible(false);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        errorLabel.setVisible(false);
        if(UIController.login(mailField.getText(),pwField.getPassword()) == false){
            errorLabel.setVisible(true);
        }
        
        else{
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_loginButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueBg;
    private javax.swing.JPanel blueBgPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel whiteBgLabel;
    private javax.swing.JPanel whiteBgPanel;
    // End of variables declaration//GEN-END:variables
}
