
package group1j.ReviewTool.UserInterface.screens;

import group1j.ReviewTool.BusinessLogic.Assignment;
import group1j.ReviewTool.BusinessLogic.User;
import group1j.ReviewTool.BusinessLogic.Group;
import group1j.ReviewTool.BusinessLogic.Student;
import group1j.ReviewTool.BusinessLogic.UReview;
import group1j.ReviewTool.UserInterface.factories.*;
import group1j.ReviewTool.UserInterface.UIController;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 * @author anilt
 * This is the InstructorScreen class:
 * Holds code generated by the NetBeans UI Builder and
 * event handling code for the UI. 
 */
public class InstructorScreen extends javax.swing.JFrame implements Refreshable{

    private static Group selectedGroup;
    private static Student selectedUser;
    private ArrayList<JPanel> switchingPanels;
    
    /**
     * Creates new form InstructorScreen
     */
    public InstructorScreen() {
        initComponents();
        setIcons();
        switchingPanels = new ArrayList<>();
        switchingPanels.add(groupsPanel);
        switchingPanels.add(assignmentsPanel);
        switchingPanels.add(selectedGroupPanel);
        switchingPanels.add(peerReviewsPanel);
    }

    public void refreshUI(){
        this.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createGroupDialog = new javax.swing.JDialog();
        cDialogPanel = new javax.swing.JPanel();
        cDialogTopInternalPanel = new javax.swing.JPanel();
        concealingPanel = new javax.swing.JPanel();
        cDialogText2 = new javax.swing.JLabel();
        cDialogTextField = new javax.swing.JTextField();
        cDialogBottomInternalPanel = new javax.swing.JPanel();
        cDialogText1 = new javax.swing.JLabel();
        cDialogScrollPane = new javax.swing.JScrollPane();
        cDialogTable = new javax.swing.JTable();
        cDialogButton = new javax.swing.JButton();
        cDialogButton.setFocusPainted(false);
        createAssignmentDialog = new javax.swing.JDialog();
        aDialogPanel = new javax.swing.JPanel();
        aDialogScrollPane = new javax.swing.JScrollPane();
        aDialogTextArea = new javax.swing.JTextArea();
        aDialogText1 = new javax.swing.JLabel();
        aDialogTextField = new javax.swing.JTextField();
        aDialogText2 = new javax.swing.JLabel();
        aDialogButton = new javax.swing.JButton();
        errorBox = new javax.swing.JDialog();
        errorBoxPanel = new javax.swing.JPanel();
        errorText = new javax.swing.JLabel();
        errorButton = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();
        groupsButton = new javax.swing.JToggleButton();
        groupsButton.setFocusPainted(false);
        assignmentsButton = new javax.swing.JToggleButton();
        assignmentsButton.setFocusPainted(false);
        topPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        showTime();
        middlePanel = new javax.swing.JPanel();
        groupsPanel = new javax.swing.JPanel();
        newGroupButton = new javax.swing.JButton();
        newGroupButton.setFocusPainted(false);
        groupsScrollPane = new javax.swing.JScrollPane();
        groupsInternalPanel = new javax.swing.JPanel();
        showInitialGroups();
        assignmentsPanel = new javax.swing.JPanel();
        assignmentsScrollPane = new javax.swing.JScrollPane();
        assignmentsInternalPanel = new javax.swing.JPanel();
        showInitialAssignments();
        newAssignmentButton = new javax.swing.JButton();
        selectedGroupPanel = new javax.swing.JPanel();
        selectedGroupScrollPane = new javax.swing.JScrollPane();
        selectedGroupInternalPanel = new javax.swing.JPanel();
        addMemberButton = new javax.swing.JButton();
        peerReviewsPanel = new javax.swing.JPanel();
        prLeftPanel = new javax.swing.JPanel();
        prLabel = new javax.swing.JLabel();
        prLabel2 = new javax.swing.JLabel();
        prScrollPane = new javax.swing.JScrollPane();
        prTextPane = new javax.swing.JTextPane();
        prLabel3 = new javax.swing.JLabel();

        createGroupDialog.setTitle("Create New Group");
        createGroupDialog.setResizable(false);
        createGroupDialog.setSize(new java.awt.Dimension(415, 340));
        createGroupDialog.setLocationRelativeTo(this);
        createGroupDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cDialogPanel.setBackground(new java.awt.Color(255, 255, 255));
        cDialogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cDialogTopInternalPanel.setBackground(new java.awt.Color(23, 35, 51));

        concealingPanel.setBackground(new java.awt.Color(23, 35, 51));

        javax.swing.GroupLayout concealingPanelLayout = new javax.swing.GroupLayout(concealingPanel);
        concealingPanel.setLayout(concealingPanelLayout);
        concealingPanelLayout.setHorizontalGroup(
            concealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        concealingPanelLayout.setVerticalGroup(
            concealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        cDialogText2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cDialogText2.setForeground(new java.awt.Color(255, 255, 255));
        cDialogText2.setText("Group Name:");

        javax.swing.GroupLayout cDialogTopInternalPanelLayout = new javax.swing.GroupLayout(cDialogTopInternalPanel);
        cDialogTopInternalPanel.setLayout(cDialogTopInternalPanelLayout);
        cDialogTopInternalPanelLayout.setHorizontalGroup(
            cDialogTopInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cDialogTopInternalPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cDialogText2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cDialogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(cDialogTopInternalPanelLayout.createSequentialGroup()
                .addComponent(concealingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cDialogTopInternalPanelLayout.setVerticalGroup(
            cDialogTopInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cDialogTopInternalPanelLayout.createSequentialGroup()
                .addComponent(concealingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cDialogTopInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cDialogText2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(cDialogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        cDialogPanel.add(cDialogTopInternalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        cDialogBottomInternalPanel.setBackground(new java.awt.Color(23, 35, 51));
        cDialogBottomInternalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cDialogText1.setBackground(new java.awt.Color(23, 35, 51));
        cDialogText1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cDialogText1.setForeground(new java.awt.Color(255, 255, 255));
        cDialogText1.setText("                               Unassigned Student List");
        cDialogBottomInternalPanel.add(cDialogText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 399, 31));

        cDialogTable.setBackground(new java.awt.Color(255, 255, 255));
        cDialogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cDialogScrollPane.setViewportView(cDialogTable);

        cDialogBottomInternalPanel.add(cDialogScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 399, 170));

        cDialogButton.setText("Create Group");
        cDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDialogButtonActionPerformed(evt);
            }
        });
        cDialogBottomInternalPanel.add(cDialogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 20));

        cDialogPanel.add(cDialogBottomInternalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 240));

        createGroupDialog.getContentPane().add(cDialogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        createAssignmentDialog.setTitle("Create New Assignment");
        createAssignmentDialog.setSize(new java.awt.Dimension(415, 340));
        createAssignmentDialog.setLocationRelativeTo(this);
        createAssignmentDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aDialogPanel.setBackground(new java.awt.Color(23, 35, 51));

        aDialogTextArea.setBackground(new java.awt.Color(255, 255, 255));
        aDialogTextArea.setColumns(20);
        aDialogTextArea.setRows(5);
        aDialogScrollPane.setViewportView(aDialogTextArea);

        aDialogText1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aDialogText1.setForeground(new java.awt.Color(255, 255, 255));
        aDialogText1.setText("Assignment Name:");

        aDialogTextField.setBackground(new java.awt.Color(255, 255, 255));

        aDialogText2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aDialogText2.setForeground(new java.awt.Color(255, 255, 255));
        aDialogText2.setText("Assignment Description:");

        aDialogButton.setText("Create Assignment");
        aDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aDialogPanelLayout = new javax.swing.GroupLayout(aDialogPanel);
        aDialogPanel.setLayout(aDialogPanelLayout);
        aDialogPanelLayout.setHorizontalGroup(
            aDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aDialogScrollPane)
                    .addGroup(aDialogPanelLayout.createSequentialGroup()
                        .addComponent(aDialogText1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aDialogTextField))
                    .addGroup(aDialogPanelLayout.createSequentialGroup()
                        .addComponent(aDialogText2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(aDialogPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(aDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        aDialogPanelLayout.setVerticalGroup(
            aDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDialogText1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aDialogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aDialogText2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aDialogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aDialogButton)
                .addGap(30, 30, 30))
        );

        createAssignmentDialog.getContentPane().add(aDialogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        errorBox.setTitle("Error");
        errorBox.setSize(new java.awt.Dimension(250, 250));
        errorBox.setLocationRelativeTo(this);
        errorBox.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorBoxPanel.setBackground(new java.awt.Color(23, 35, 51));

        errorText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 255, 255));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorText.setText("ERROR TEXT");

        errorButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorButton.setText("OK");
        errorButton.setBorderPainted(false);
        errorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorBoxPanelLayout = new javax.swing.GroupLayout(errorBoxPanel);
        errorBoxPanel.setLayout(errorBoxPanelLayout);
        errorBoxPanelLayout.setHorizontalGroup(
            errorBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(errorBoxPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(errorButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        errorBoxPanelLayout.setVerticalGroup(
            errorBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorBoxPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(errorButton)
                .addGap(24, 24, 24))
        );

        errorBox.getContentPane().add(errorBoxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 220));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ReviewTool");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(23, 35, 51));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupsButton.setBackground(new java.awt.Color(23, 35, 51));
        buttonGroup1.add(groupsButton);
        groupsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        groupsButton.setForeground(new java.awt.Color(255, 255, 255));
        groupsButton.setText("Groups");
        groupsButton.setBorder(null);
        groupsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsButtonActionPerformed(evt);
            }
        });
        leftPanel.add(groupsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 80));

        assignmentsButton.setBackground(new java.awt.Color(23, 35, 51));
        buttonGroup1.add(assignmentsButton);
        assignmentsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        assignmentsButton.setForeground(new java.awt.Color(255, 255, 255));
        assignmentsButton.setText("Assignments");
        assignmentsButton.setBorder(null);
        assignmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentsButtonActionPerformed(evt);
            }
        });
        leftPanel.add(assignmentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 90));

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 640));

        topPanel.setBackground(new java.awt.Color(71, 120, 199));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("   UserName");
        usernameLabel.setText("User: " + UIController.getCurrentUser().getName());

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 614, Short.MAX_VALUE)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1140, 80));

        middlePanel.setBackground(new java.awt.Color(255, 255, 255));
        middlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupsPanel.setBackground(new java.awt.Color(255, 255, 255));
        groupsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newGroupButton.setBackground(new java.awt.Color(255, 255, 255));
        newGroupButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newGroupButton.setForeground(new java.awt.Color(0, 0, 0));
        newGroupButton.setText("Create New Group");
        newGroupButton.setBorder(null);
        newGroupButton.setFocusPainted(false);
        newGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupButtonActionPerformed(evt);
            }
        });
        groupsPanel.add(newGroupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 250, 40));

        groupsInternalPanel.setBackground(new java.awt.Color(255, 255, 255));
        groupsInternalPanel.setAlignmentY(0.0F);
        groupsInternalPanel.setLayout(new javax.swing.BoxLayout(groupsInternalPanel, javax.swing.BoxLayout.Y_AXIS));
        groupsScrollPane.setViewportView(groupsInternalPanel);

        groupsPanel.add(groupsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1140, 520));

        middlePanel.add(groupsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1140, 560));

        assignmentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        assignmentsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignmentsInternalPanel.setBackground(new java.awt.Color(255, 255, 255));
        assignmentsInternalPanel.setLayout(new javax.swing.BoxLayout(assignmentsInternalPanel, javax.swing.BoxLayout.Y_AXIS));
        assignmentsScrollPane.setViewportView(assignmentsInternalPanel);

        assignmentsPanel.add(assignmentsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1140, 520));

        newAssignmentButton.setBackground(new java.awt.Color(255, 255, 255));
        newAssignmentButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newAssignmentButton.setForeground(new java.awt.Color(0, 0, 0));
        newAssignmentButton.setText("Create New Assignment");
        newAssignmentButton.setBorder(null);
        newAssignmentButton.setFocusPainted(false);
        newAssignmentButton.setMaximumSize(new java.awt.Dimension(168, 40));
        newAssignmentButton.setMinimumSize(new java.awt.Dimension(168, 40));
        newAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAssignmentButtonActionPerformed(evt);
            }
        });
        assignmentsPanel.add(newAssignmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 230, 40));

        middlePanel.add(assignmentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1140, 560));

        selectedGroupPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectedGroupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectedGroupScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        selectedGroupInternalPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectedGroupInternalPanel.setLayout(new javax.swing.BoxLayout(selectedGroupInternalPanel, javax.swing.BoxLayout.Y_AXIS));
        selectedGroupScrollPane.setViewportView(selectedGroupInternalPanel);

        selectedGroupPanel.add(selectedGroupScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1140, 520));

        addMemberButton.setBackground(new java.awt.Color(255, 255, 255));
        addMemberButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addMemberButton.setForeground(new java.awt.Color(0, 0, 0));
        addMemberButton.setText("Add New Members");
        addMemberButton.setToolTipText("");
        addMemberButton.setBorder(null);
        addMemberButton.setBorderPainted(false);
        addMemberButton.setFocusPainted(false);
        addMemberButton.setMaximumSize(new java.awt.Dimension(168, 40));
        addMemberButton.setMinimumSize(new java.awt.Dimension(168, 40));
        addMemberButton.setPreferredSize(new java.awt.Dimension(168, 40));
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });
        selectedGroupPanel.add(addMemberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 250, 40));

        middlePanel.add(selectedGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1140, 560));

        peerReviewsPanel.setBackground(new java.awt.Color(255, 255, 255));
        peerReviewsPanel.setMinimumSize(new java.awt.Dimension(1140, 560));
        peerReviewsPanel.setPreferredSize(new java.awt.Dimension(1140, 560));
        peerReviewsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prLeftPanel.setBackground(new java.awt.Color(23, 35, 51));
        prLeftPanel.setMaximumSize(new java.awt.Dimension(250, 560));
        prLeftPanel.setMinimumSize(new java.awt.Dimension(250, 560));
        prLeftPanel.setPreferredSize(new java.awt.Dimension(250, 560));
        prLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        peerReviewsPanel.add(prLeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 210, 480));

        prLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prLabel.setText(" Member List");
        peerReviewsPanel.add(prLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 80));

        prLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prLabel2.setText("Select a reviewer from the member list");
        peerReviewsPanel.add(prLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 930, 160));

        prScrollPane.setBorder(null);

        prTextPane.setEditable(false);
        prTextPane.setBackground(new java.awt.Color(255, 255, 255));
        prTextPane.setBorder(null);
        prTextPane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prScrollPane.setViewportView(prTextPane);

        peerReviewsPanel.add(prScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 880, 330));

        prLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peerReviewsPanel.add(prLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 300, 70));

        middlePanel.add(peerReviewsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1140, 560));

        getContentPane().add(middlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 1140, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    ** This is event handling code for "New Group Button" in the "Groups" screen
    ** Creates a dialog box where the user can create a new group
    ** Creates an error box if there are no students in the freeUserList
    */
    private void newGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupButtonActionPerformed
        try{
            ArrayList<User> userList = UIController.getFreeUserList();
            if(userList.size() == 0){
                throw new Exception("0");
            }
            createAssignmentDialog.setVisible(false);
            createGroupDialog.setVisible(true);
            concealingPanel.setVisible(false);
            cDialogButton.setText("Create Group");
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel ) cDialogTable.getModel();
            model.setRowCount(0);
            for(User u: userList){
                model.addRow(new Object[]{u.getName(),u.getId(),false});
            }
        }
        catch(Exception e){
            errorBox.setVisible(true);
            errorText.setText("There are no unassigned students!");
        }
        
    }//GEN-LAST:event_newGroupButtonActionPerformed

    /*
    ** Switch to "Groups" screen
    */
    private void groupsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsButtonActionPerformed
        switchPanel("groups");
    }//GEN-LAST:event_groupsButtonActionPerformed

    /*
    ** Switch to assignments screen
    */
    private void assignmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentsButtonActionPerformed
        switchPanel("assignments");
    }//GEN-LAST:event_assignmentsButtonActionPerformed

    /*
    ** Event handling code for "Create Group" button in the dialog box
    ** Gets entered group name and selected IDs, sends it to UIController class
    ** Refreshes UI in the end to account for the new group
    ** Creates an error box if the name field is empty or
    ** no students are selected.
    */
    private void cDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDialogButtonActionPerformed
        try{
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel ) cDialogTable.getModel();
            ArrayList<Integer> selectedIDs = new ArrayList<Integer>();
            for(int i = 0; i < model.getRowCount();i++){
                if((boolean) model.getValueAt(i,2) == true){
                    selectedIDs.add((int)model.getValueAt(i, 1));
                }
            }
            
            if(selectedIDs.size() == 0){
                throw new Exception("1");
            }
            if(groupsPanel.isVisible() == true){
                String groupName = cDialogTextField.getText();
                if(groupName.equals("")){
                    throw new Exception("0");
                }
                UIController.createGroup(selectedIDs,groupName); 
                addGroupToUI(UIController.getGlobalGroupList().get(UIController.getGlobalGroupList().size()-1));
            }
            else if(selectedGroupPanel.isVisible() == true){
                UIController.addMembers(selectedIDs,selectedGroup.getName());
                showGroupMembers();
            }
            createGroupDialog.setVisible(false);
            this.revalidate();
            cDialogTextField.setText("");
        }
        catch(Exception e){
            switch(e.getMessage()){
                case "0":
                    errorText.setText("Group name cannot be blank!");
                    errorBox.setVisible(true);
                    break;
                case "1":
                    errorText.setText("No students are selected!");
                    errorBox.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_cDialogButtonActionPerformed

    /*
    ** Creates a dialog box for entering details for a new assignment
    */
    private void newAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAssignmentButtonActionPerformed
        createGroupDialog.setVisible(false);
        createAssignmentDialog.setVisible(true);
    }//GEN-LAST:event_newAssignmentButtonActionPerformed

    /*
    ** Event handling code for "Create Assignment" button in the dialog box
    ** Gets entered assignment details, sends it to UIController class
    ** Refreshes UI in the end to account for the new assignment
    ** Creates an error box if assignment name or description is empty
    */
    private void aDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aDialogButtonActionPerformed
        try{
            String aName = aDialogTextField.getText();
            String aDesc = aDialogTextArea.getText();
            if(aName.equals("") || (aDesc.equals(""))){
                throw new Exception("0");
            }
            
            UIController.createAssignment(aName,aDesc);
            addAssignmentToUI(new Assignment(aName,aDesc));
            this.revalidate();
            aDialogTextField.setText("");
            aDialogTextArea.setText("");
            createAssignmentDialog.setVisible(false);
        }
        catch(Exception e){
            errorText.setText("Both fields must be filled!");
            errorBox.setVisible(true);
        }
    }//GEN-LAST:event_aDialogButtonActionPerformed

    /*
    ** Exact same as "Create New Group" button,
    ** but changes the text.
    */
    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        try{
            ArrayList<User> userList = UIController.getFreeUserList();
            if(userList.size() == 0){
                throw new Exception("0");
            }
            createAssignmentDialog.setVisible(false);
            createGroupDialog.setVisible(true);
            concealingPanel.setVisible(true);
            cDialogButton.setText("Add member(s)");
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel ) cDialogTable.getModel();
            model.setRowCount(0);
            for(User u: userList){
                model.addRow(new Object[]{u.getName(),u.getId(),false});
            }
        }
        catch(Exception e){
            errorBox.setVisible(true);
            errorText.setText("There are no unassigned students!");
        }
    }//GEN-LAST:event_addMemberButtonActionPerformed

    // NEEDS IMPLEMENTATION
    private void errorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorButtonActionPerformed
        // TODO add your handling code here:
        errorBox.setVisible(false);
    }//GEN-LAST:event_errorButtonActionPerformed

    private void switchPanel(String type){
        for(JPanel pn: switchingPanels){
            pn.setVisible(false);
        }
        
        if(type.equalsIgnoreCase("groups")){
            groupsPanel.setVisible(true);
        }
        
        else if(type.equalsIgnoreCase("assignments")){
            assignmentsPanel.setVisible(true);
        }
        
        else if(type.equalsIgnoreCase("selectedGroup")){
            selectedGroupPanel.setVisible(true);
        }
        
        else if(type.equalsIgnoreCase("peerReviews")){
            peerReviewsPanel.setVisible(true);
        }
        
        prLeftPanel.removeAll();
    }
    
    /*
    ** Event handling code for "View Group" button (eye symbol)
    ** Shows an empty panel for displaying the selected group.
    ** The panel is filled by showGroupMembers() function
    */
    public void groupViewButtonActionPerformed(String groupName){
        ArrayList<Group> allGroups = UIController.getGlobalGroupList();
        for(Group gr: allGroups){
            if(gr.getName().equals(groupName)){
                selectedGroup = gr;
                break;
            }
        }
        switchPanel("selectedGroup");
        showGroupMembers();
    }
    
    // NEEDS IMPLEMENTATION
    private void assignmentViewButtonActionPerformed(String aName){
        
    }
    
    // Removes the selected user from group and refreshes UI
    private void removeMemberButtonActionPerformed(java.awt.event.ActionEvent evt){
        int id = Integer.parseInt(((JButton)evt.getSource()).getName());
        UIController.removeMember(id);
        showGroupMembers();
    }
    
    
    private void viewReviewsButtonActionPerformed(User targetUser){
        selectedUser = ((Student) targetUser);
        switchPanel("peerReviews");
        int count = 0;
        for(UReview ur: selectedUser.getReviews()){
            count++;
            UIPanel smallMemberPanel = PanelFactory.createPanel("smallMember");
            buttonGroup2.add(smallMemberPanel.getToggleButton());
            
            for(User reviewer: selectedGroup.getMembers()){
                if(reviewer.getId() == ur.getReviewer().getId()){
                    smallMemberPanel.getToggleButton().setText(reviewer.getName());
                    
                    smallMemberPanel.getToggleButton().addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            smallMemberButtonActionPerformed(ur,reviewer.getName());
                        }
                    });
                    
                    break;
                }
            }
            
            prLabel2.setText("Select a reviewer from the member list");
            prTextPane.setText("");
            prLabel3.setText("");
            prLeftPanel.add(smallMemberPanel);
            buttonGroup2.clearSelection();
        }
        
        if(count == 0){
            prLabel2.setText("No reviews made for" + selectedUser.getName() + "yet");
            prTextPane.setText("");
            prLabel3.setText("");
        }
    }
    
    private void smallMemberButtonActionPerformed(UReview ur,String reviewerName){
        prLabel2.setText(reviewerName + "'s Peer Review of" + selectedUser.getName());
        prTextPane.setText("   " + ur.getComment());
        prLabel3.setText("Point: " + ur.getPoint()+ "/10");
    }
    
    /*
    ** Adds a single group to the "Groups" panel display
    ** Gets called as many times as there are existing groups
    ** Also gets called when a new group is created
    ** The group panel is created by PanelFactory
    */
    private void addGroupToUI(Group gr){
        UIPanel newGroupPanel = PanelFactory.createPanel("group");
        
        newGroupPanel.setLabel(gr.getName());
        
        newGroupPanel.getViewButton().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupViewButtonActionPerformed(gr.getName());
            }
        });
        
        groupsInternalPanel.add(newGroupPanel);
        groupsInternalPanel.add(javax.swing.Box.createVerticalGlue());
    }
    
    /*
    ** Adds a single assignment to the "Assigments" panel display
    ** Gets called as many times as there are existing assignments
    ** Also gets called when a new assignment is created
    ** The assignment panel is created by PanelFactory
    */
    private void addAssignmentToUI(Assignment a){
        
        UIPanel newAssignmentPanel = PanelFactory.createPanel("assignment");
        
        newAssignmentPanel.setLabel(a.getName());
            
        newAssignmentPanel.getViewButton().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentViewButtonActionPerformed(a.getName());
            }
        });
            
        assignmentsInternalPanel.add(newAssignmentPanel);
        assignmentsInternalPanel.add(javax.swing.Box.createVerticalGlue());
    }
    
    /*
    ** Adds a single group member to the "View Group" panel display
    ** Gets called as many times as there are existing members
    ** Also gets called when a member is added or removed
    ** The member panel is created by PanelFactory
    */
    private void addMemberToUI(User u){
        
        UIPanel newMemberPanel = PanelFactory.createPanel("member");
        
        newMemberPanel.setLabel(u.getId() + "," + u.getName());
        
        newMemberPanel.getRemoveButton().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemberButtonActionPerformed(evt);
            }
        });
        newMemberPanel.getReviewButton().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReviewsButtonActionPerformed(u);
            }
        });
        
        selectedGroupInternalPanel.add(newMemberPanel);
        selectedGroupInternalPanel.add(javax.swing.Box.createVerticalGlue());
        
    }

    /*
    ** Adds inital data stored in permanent data to the UI 
    */
    private void showInitialAssignments(){
        ArrayList<Group> groupData= UIController.getGlobalGroupList();
        ArrayList<Assignment> assignmentData = groupData.get(0).getAssignments();
        for(Assignment a : assignmentData){
            addAssignmentToUI(a);
        }
        assignmentsScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    /*
    ** Adds inital data stored in permanent data to the UI 
    */
    private void showInitialGroups(){
        ArrayList<Group> groupData= UIController.getGlobalGroupList();
        for(Group gr : groupData){
            addGroupToUI(gr);
        }
        groupsScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    /*
    ** Adds inital data stored in permanent data to the UI 
    */
    private void showGroupMembers(){
        selectedGroupInternalPanel.removeAll();
        for(User u:selectedGroup.getMembers()){
            addMemberToUI(u);
        }
        selectedGroupScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    /*
    ** Shows time on the top right corner
    */
    public void showTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                timeLabel.setText(new SimpleDateFormat("H:mm:ss").format(new Date()));
                timeLabel.repaint();
            }
        });
        timeLabel.setText(new SimpleDateFormat("H:mm:ss").format(new Date()));
        timer.start();
        
    }
    
    /*
    ** Display icons in the "img" folder
    */
    public void setIcons(){
        newGroupButton.setIcon(new javax.swing.ImageIcon("src\\main\\java\\group1j\\ReviewTool\\UserInterface\\img\\add.png"));
        newAssignmentButton.setIcon(new javax.swing.ImageIcon("src\\main\\java\\group1j\\ReviewTool\\UserInterface\\img\\add.png"));
        addMemberButton.setIcon(new javax.swing.ImageIcon("src\\main\\java\\group1j\\ReviewTool\\UserInterface\\img\\add.png"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aDialogButton;
    private javax.swing.JPanel aDialogPanel;
    private javax.swing.JScrollPane aDialogScrollPane;
    private javax.swing.JLabel aDialogText1;
    private javax.swing.JLabel aDialogText2;
    private javax.swing.JTextArea aDialogTextArea;
    private javax.swing.JTextField aDialogTextField;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JToggleButton assignmentsButton;
    private javax.swing.JPanel assignmentsInternalPanel;
    private javax.swing.JPanel assignmentsPanel;
    private javax.swing.JScrollPane assignmentsScrollPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cDialogBottomInternalPanel;
    private javax.swing.JButton cDialogButton;
    private javax.swing.JPanel cDialogPanel;
    private javax.swing.JScrollPane cDialogScrollPane;
    private javax.swing.JTable cDialogTable;
    private javax.swing.JLabel cDialogText1;
    private javax.swing.JLabel cDialogText2;
    private javax.swing.JTextField cDialogTextField;
    private javax.swing.JPanel cDialogTopInternalPanel;
    private javax.swing.JPanel concealingPanel;
    private javax.swing.JDialog createAssignmentDialog;
    private javax.swing.JDialog createGroupDialog;
    private javax.swing.JDialog errorBox;
    private javax.swing.JPanel errorBoxPanel;
    private javax.swing.JButton errorButton;
    private javax.swing.JLabel errorText;
    private javax.swing.JToggleButton groupsButton;
    private javax.swing.JPanel groupsInternalPanel;
    private javax.swing.JPanel groupsPanel;
    private javax.swing.JScrollPane groupsScrollPane;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JButton newAssignmentButton;
    private javax.swing.JButton newGroupButton;
    private javax.swing.JPanel peerReviewsPanel;
    private javax.swing.JLabel prLabel;
    private javax.swing.JLabel prLabel2;
    private javax.swing.JLabel prLabel3;
    private javax.swing.JPanel prLeftPanel;
    private javax.swing.JScrollPane prScrollPane;
    private javax.swing.JTextPane prTextPane;
    private javax.swing.JPanel selectedGroupInternalPanel;
    private javax.swing.JPanel selectedGroupPanel;
    private javax.swing.JScrollPane selectedGroupScrollPane;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}

